# Generated by Django 4.0.5 on 2022-06-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.IntegerField(),
        ),
    ]
